# Generated by Django 4.0.2 on 2022-02-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title name')),
                ('description', models.TextField(verbose_name='Desc field')),
                ('img_url', models.ImageField(upload_to='author/img/blogs/', verbose_name='Blog photo')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
