# Generated by Django 4.0.2 on 2022-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
