# Generated by Django 4.0.1 on 2022-04-05 04:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0013_profileifo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileIfo',
            new_name='ProfileInfo',
        ),
    ]
