# Generated by Django 4.0.1 on 2022-04-21 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0015_profileinfo_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
        migrations.AddField(
            model_name='blogs',
            name='disliked',
            field=models.ManyToManyField(related_name='disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
