# Generated by Django 4.0.1 on 2022-04-12 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0015_profileinfo_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
